/*
 * KubeClarity APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dto_application_resource

type ApplicationResource struct {
	Id                     string        `json:"id,omitempty"`
	ResourceName           string        `json:"resourceName,omitempty"`
	ResourceHash           string        `json:"resourceHash,omitempty"`
	ResourceType           *ResourceType `json:"resourceType,omitempty"`
	Vulnerabilities        int32         `json:"vulnerabilities,omitempty"`
	Applications           int32         `json:"applications,omitempty"`
	Packages               int32         `json:"packages,omitempty"`
	ReportingSBOMAnalyzers []string      `json:"reportingSBOMAnalyzers,omitempty"`
}
