# syntax=docker/dockerfile:experimental
# ---
FROM golang:1.20 AS build

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0

WORKDIR /work
COPY webhook .

# Build admission-webhook
RUN --mount=type=cache,target=/root/.cache/go-build,sharing=private \
  go build -o bin/keel-webhook .

# ---
FROM scratch AS run

COPY --from=build /work/bin/keel-webhook /usr/local/bin/

CMD ["keel-webhook"]