kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scanyourkube-job.clusterRoleBindingName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "scanyourkube-job.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "scanyourkube-job.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io