kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "scanyourkube-job.clusterRoleName" . }}
{{- with .Values.scanyourkubejob.clusterRole.rules }}
rules:
  {{- toYaml . | nindent 2 }} 
{{- end }}
