{{- if .Values.scanyourkubejob.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scanyourkube-job.serviceAccountName" . }}
  labels:
    {{- include "scanyourkube-job.labels" . | nindent 4 }}
  {{- with .Values.scanyourkubejob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
