/*
 * KubeClarity APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package scan

// ScanType : scan type
type ScanType string

// List of ScanType
const (
	QUICK    ScanType = "QUICK"
	SCHEDULE ScanType = "SCHEDULE"
)
