/*
 * KubeClarity APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package scan

type RuntimeScanConfig struct {
	Namespaces []string `json:"namespaces,omitempty"`
}
