/*
 * KubeClarity APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package scan

// RuntimeScanStatus : Status of a runtime scan
type RuntimeScanStatus string

// List of RuntimeScanStatus
const (
	NOT_STARTED RuntimeScanStatus = "NOT_STARTED"
	IN_PROGRESS RuntimeScanStatus = "IN_PROGRESS"
	FINALIZING  RuntimeScanStatus = "FINALIZING"
	DONE        RuntimeScanStatus = "DONE"
)
