/*
 * KubeClarity APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dto_application

import dto_vulnerability "github.com/scanyourkube/cronjob/dto/api/vulnerability"

type Application struct {
	Id              string           `json:"id,omitempty"`
	ApplicationName string           `json:"applicationName,omitempty"`
	ApplicationType *ApplicationType `json:"applicationType,omitempty"`
	Labels          []string         `json:"labels,omitempty"`
	// vulnerability count per severity
	Vulnerabilities      []dto_vulnerability.VulnerabilityCount `json:"vulnerabilities,omitempty"`
	Environments         []string                               `json:"environments,omitempty"`
	ApplicationResources int32                                  `json:"applicationResources,omitempty"`
	Packages             int32                                  `json:"packages,omitempty"`
}
