/*
 * KubeClarity APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dto_application

type ApplicationType string

// List of ApplicationType
const (
	POD       ApplicationType = "POD"
	DIRECTORY ApplicationType = "DIRECTORY"
	LAMBDA    ApplicationType = "LAMBDA"
)
