{{- if .Values.scanyourkubewebhook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keel-webhook.serviceAccountName" . }}
  labels:
    {{- include "keel-webhook.labels" . | nindent 4 }}
  {{- with .Values.scanyourkubewebhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
