apiVersion: v1
kind: Service
metadata:
  name: {{ include "keel-webhook.fullname" . }}
  labels:
    {{- include "keel-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scanyourkubewebhook.service.type }}
  ports:
    - port: {{ .Values.scanyourkubewebhook.service.port }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "keel-webhook.selectorLabels" . | nindent 4 }}
