apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.scanyourkubewebhook.certificate.rootCertificate.name }}
  namespace: {{ .Release.Namespace }}
spec:
  # Secret names are always required.
  secretName: {{ .Values.scanyourkubewebhook.certificate.rootCertificate.secretName }}
  isCA: true
  commonName: {{ .Values.scanyourkubewebhook.certificate.rootCertificate.commonName }}
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: {{ .Values.scanyourkubewebhook.certificate.selfSignedIssuer.name }}
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: {{ .Values.scanyourkubewebhook.certificate.selfSignedIssuer.kind }}
    group: cert-manager.io
