apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.scanyourkubewebhook.certificate.clusterIssuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Values.scanyourkubewebhook.certificate.rootCertificate.secretName }}